# kubectl create -f echo-dep.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-dep
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
        - name: echo-c
          image: jdxj/echo:0.1.0
          volumeMounts:
            - mountPath: /study_k8s/config
              readOnly: true
              name: echo-cfg
      volumes:
        - name: echo-cfg
          configMap:
            name: study-k8s-config
            items:
              - key: config.yaml
                path: config.yaml