// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: message.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Echo service

func NewEchoEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Echo service

type EchoService interface {
	Hello(ctx context.Context, in *Ping, opts ...client.CallOption) (*Pong, error)
}

type echoService struct {
	c    client.Client
	name string
}

func NewEchoService(name string, c client.Client) EchoService {
	return &echoService{
		c:    c,
		name: name,
	}
}

func (c *echoService) Hello(ctx context.Context, in *Ping, opts ...client.CallOption) (*Pong, error) {
	req := c.c.NewRequest(c.name, "Echo.Hello", in)
	out := new(Pong)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Echo service

type EchoHandler interface {
	Hello(context.Context, *Ping, *Pong) error
}

func RegisterEchoHandler(s server.Server, hdlr EchoHandler, opts ...server.HandlerOption) error {
	type echo interface {
		Hello(ctx context.Context, in *Ping, out *Pong) error
	}
	type Echo struct {
		echo
	}
	h := &echoHandler{hdlr}
	return s.Handle(s.NewHandler(&Echo{h}, opts...))
}

type echoHandler struct {
	EchoHandler
}

func (h *echoHandler) Hello(ctx context.Context, in *Ping, out *Pong) error {
	return h.EchoHandler.Hello(ctx, in, out)
}
